language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install
script:
  - npm run kss

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: styleguide
  on:
    branch: master
